### ISSUE TITLE
Ajouter le(s) speaker(s) sur chaque talk du programme 

### ISSUE THREAD

**Issue by eheb** [breizhcamp/www-old#15]
Ajouter le(s) speaker(s) sur chaque talk du programme qui sera 1 lien vers sa bio.

**Comment by ndeloof** [comment]
c'est déjà le cas !

**Comment by eheb** [comment]
ajouter le nom du speaker en hyperlien vers sa bio dans chaque talk du programme, comme au devoxxFR 2013 et Agile tour Rennes 2012
