### ISSUE TITLE
Page des speakers : liens non mis en évidence

### ISSUE THREAD

**Issue by lauterry** [breizhcamp/www-old#6]
Bonjour

Juste une remarque ne terme de User Experience.

Dans la page des speakers, il n'est évident qu'en cliquant sur le nom, cela ouvre la bio du speaker ni qu'il existe un lien qui permet d'ouvrir le descriptif de la présentation juste en dessus.

En fait, le lien qui correspond au nom du speaker est trop rapproché de l'intitulé de la prez. Il n'est alors pas évident qu'il y ai deux liens différents.

Une autre approche serait de rendre cliquable l'avatar du speaker qui afficherait sa bio plutot que via son nom.

Juste un feedback de ma part :)

Thierry

**Comment by ybonnel** [comment]
Comment mettre en avant que l'image est cliquable ?

**Comment by ybonnel** [comment]
T'as le droit de faire une pull request ;)

**Comment by lauterry** [comment]
En modifiant le curseur de la souris au passage de l'image

et/ou

En ajoutant une surbrillance autour de l'image grâce au CSS
